### PR TITLE
Multiple minor improvements and additional implementations

### PR DESCRIPTION
**Pull request by theimo1221**
Hello @zVolodymyr,

working with your library we made some changes to reduce differences between rendering of this library and opening file in Word itself.

This PR contains:
- [x]  Recursive  style-format interpreation (e.g. `a` based on `b` based on `c`; previously `a` only contained the styles from `b` before `b` loaded it's additional styles from `c`, due to alphabetical order)
- [x]  Preserve `page-breaks` immediatly before images
- [x]  Improve page-break logic, e.g. to break before `bookmarkStart` instead between `bookmarkStart` and the headline text
- [x]  ~Use `themes1.xml`~ **Use parsed themes** to gather Font info for `asciiTheme` (e.g. `majorHAnsi`)
- [x]  Option `noStyleBlock` for CSP restrictive apps
- [x]  Use `IDomStyle.isDefault` to update information on `IDomStyle.Id === null`
- [x] ~Respect `tableWidthStyle=auto`~ **Fixed in Master**
- [x]  ~Prevent invalid duplicate width description on colgroups (e.g. `170.8ptpx`)~ **Fixed in Master**
- [x] Respect first-page-different with header/footer
- [x] Use Page Count within section for first/even page detection regarding header/footer
- [x] Don't convert size Attributes which are already in pt units.  

I hope you find these changes useful.
Feel free to ask any uprising questions and to make changes directly in my branch.

Best regards

Thiemo

### CODE REVIEW

**Comment by theimo1221** [comment]
I synced this branch with your changes.
Currently I'm working on using your wdlFooter to render the proper footer.

**Comment by theimo1221** [comment]
Synced again, adding some fixes in regards to "First page different" and using the specific sections page number instead of global page number

**Comment by isocroft** [comment]
@theimo1221 niced work here!!! Awesome!

Can you resolve the conflict anytime soon ?

**Comment by theimo1221** [comment]
> @theimo1221 nice work here!!! Awesome!
> 
> Can you resolve the conflict anytime soon ?

@isocroft All remaining merge conflicts are resolved

**Comment by zVolodymyr** [comment]
@theimo1221 I'm glad you resolved your issue with CSP. However I see this issue as edge case and don't think option to render style directly into elements should be part of library, moreover having such option brings implementation limitation in future

P. S. At this moment there is no other people related to this repository, except repository owner. Be aware of this when you receive any directions regarging PR.

**Comment by theimo1221** [comment]
> @theimo1221 I'm glad you resolved your issue with CSP. However I see this issue as edge case and don't think option to render style directly into elements should be part of library, moreover having such option brings implementation limitation in future
> 
> P. S. At this moment there is no other people related to this repository, except repository owner. Be aware of this when you receive any directions regarging PR.

@zVolodymyr I'm not sure, but I think, there is a misunderstanding here.
This PR contains all improvements and adjustment we needed in regards to several example files.
So while indeed a small portion is for #12 all the other changes in this PR will work without the new option as well adressing these topics:

- [x]  Recursive  format-template interpreation (e.g. `a` based on `b` based on `c`; previously `a` only contained the styles from `b` before `b` loaded it's additional styles from `c`, due to alphabetical order)
- [x]  Preserve `page-breaks` immediatly before images
- [x]  Improve page-break logic, e.g. to break before `bookmarkStart` instead between `bookmarkStart` and the headline text
- [x]  ~Use `themes1.xml`~ **Use parsed themes** to gather Font info for `asciiTheme` (e.g. `majorHAnsi`)
- [x]  Use `IDomStyle.isDefault` to update information on `IDomStyle.Id === null`
- [x]  ~Respect `tableWidthStyle=auto`~ **Fixed in Master**
- [x]  ~Prevent invalid duplicate width description on colgroups (e.g. `170.8ptpx`)~ **Fixed in Master**
- [x]  Respect first-page-different with header/footer
- [x]  Use Page Count within section for first/even page detection regarding header/footer
- [x]  Don't convert size Attributes which are already in pt units.  


The `noStyleBlock` option, just interacts with the needed central places in regards to building up the css block and afterwards assigns these css rules by js. This option doesn't interfere with the normal rendering with style block.
Furthermore I think the other minor improvements and adjustments are helpfull for others too, like e.g. the recursive format-template resolving or the improved page-breaking which respects `bookmarkStart` Elements, and so on.

Feel free to contact me via e-mail. If you want we could setup a call, so we could talk about those changes.

**Comment by isocroft** [comment]
@zVolodymyr hello to you.

Is there any other review that needs to be done on this PR ? I don't mean to be too forward. I am just curious.

Thank you.

**Comment by isocroft** [comment]
@theimo1221 I believe @zVolodymyr will consider this PR for review and then merging after you fix the conflict.

**Comment by theimo1221** [comment]
> P. S. At this moment there is no other people related to this repository, except repository owner. Be aware of this when you receive any directions regarging PR.

@isocroft As stated here, I don`t think you can push zVolodymyr to do it.


But I`ll look into it these days and update my PR accordingly

**Comment by WGTW** [comment]
Hopefully this fantastic PR will be merged soon, am in need of these new changes.

**Comment by ammad172** [comment]
> @zVolodymyr hello to you.
> 
> Is there any other review that needs to be done on this PR ? I don't mean to be too forward. I am just curious.
> 
> Thank you.

Can you help me? i am stuck with my base 64 for docx file data which i need to preview but i am not able to do it in angular 8. Can you guide me the code snippet how can we do it in angular 8

**Comment by theimo1221** [comment]
> Is there any update to this pr? looks amazing.

As my PR got ignored and keeping the branch in sync was kinda time expensive (as I changed quite a bit) and the solution wasn't good enough for my project I dropped it.

**Pull request closed without merging**
